### ISSUE TITLE
Mac OS Test

### ISSUE THREAD

**Issue by psychstatistics** [stan-dev/statastan#1]
I was able to get StataStan working on:

Mac OS 10.10.3
Stata 14.0
CmdStan 2.6.2

I couldn't make Version 2 of the .do file examples work (the one where Stata searches in the temp directory). It just said it could find the file or the global macro.  Version 1 and Version 4 worked fine. I'll test out some of my own models soon and let you know if they work as well.

**Comment by robertgrant** [comment]
Great, thanks for that. It would help to see a log file of the one that didn't work, preferably with 

```
set trace on
```

If you could paste that here, I'll see if anything comes to mind. otherwise I'll have to defer to a Mac using contributor.

**Comment by robertgrant** [comment]
Hi, if you get a chance, try out the latest version in alpha-test. I fixed the prefixes that Stata assigns to do-files in the tmpdir, and that might have fixed your problem. If so, hooray! we are going to beta.

**Comment by psychstatistics** [comment]
Sorry, I never got back to you previously. I've run all four models and everything works just great.  Let me know how else I can help out. 

Is there any plan to be able to use Stata's graphical summaries for Bayesian models?

**Comment by robertgrant** [comment]
Fantastic, thanks for that. Master branch, here we come.

Yes, I want to try integrating the Stan outputs with the bayes graph commands that are new in Stata, but if that proves tricky, we can reproduce them easily in our own commands.

Sent by Outlook for Android

Robert Grant

Senior Lecturer in health & social care statistics

Kingston University & St George's, University of London

www.robertgrantstats.co.uk

On Mon, Aug 24, 2015 at 1:56 PM -0700, "psychstatistics" notifications@github.com wrote:
Sorry, I never got back to you previously. I've run all four models and everything works just great.  Let me know how else I can help out.

Is there any plan to be able to use Stata's graphical summaries for Bayesian models?

---
