### ISSUE TITLE
Select which parameters to be printed

### ISSUE THREAD

**Issue by psychstatistics** [stan-dev/statastan#7]
Hopefully, I didn't just miss the option that does this, but I was wondering if there is a way to select only a few of parameters to be printed (and saved). I tested this out on a hierarchical model with a about a 1000 parameters. Everything works great, but the output is busy because there are so many parameters.

**Comment by robertgrant** [comment]
Yes, you could filter the contents of the Stan output at the point where it gets trimmed and copied into a CSV format for Stata. Or you could get them all in through the 'load' option but only display some of the stats with 'tabstat'. But I don't know about cutting down the Stan output itself, and that all gets displayed inside the results window. Do you want me to assign this one to you?

**Comment by robertgrant** [comment]
I'm going to regard this as having two parts: Stan makes lots of output (not so much now that stansummary is separated out) and Stata makes lots of output (which is going to be fixed by having a noprintsummary option). So this gets closed but is fixed elsewhere.
