### ISSUE TITLE
Simple pull request

### ISSUE THREAD

**Issue by wbuchanan** [stan-dev/statastan#9]
Hey,

I forked the repo and built out a simple gh-pages branch so users can use

```
net inst statastan, from("https://wbuchanan.github.io/statastan")
```

That could potentially be useful for others who may want to work with the most current version of Stata Stan.  There isn't a way to submit the pull request for the new branch, but I just took the README and moved the example files into the main directory to make it easier for the .pkg file to locate and move the files.

**Comment by robertgrant** [comment]
That is great - I was just starting to think about that. Now let me see if we can merge in your changes or recreate them... I'm not much of a githead so if you've got any ideas do let me know!

**Comment by wbuchanan** [comment]
You should be able to do something like:

```
git branch gh-pages
git push -u origin gh-pages
```

To create and add the gh-pages branch.  Then I should be able to submit a pull request (although it is entirely possible that it might require a bit of manual merging).

**Comment by bob-carpenter** [comment]
@wbuchanan  You should be able to submit a pull request from your end.  You need to clone our repo, make the branch, then create a pull request from your branch with a statastan branch as a target.

Here's an example of an external pull request for Stan:

https://github.com/stan-dev/stan/pull/1762

**Comment by wbuchanan** [comment]
@bob-carpenter my concern was more that there wasn't a gh-pages branch that I could submit the pull request against, but I just submitted it using the master branch as the base.

**Comment by bob-carpenter** [comment]
OK, that makes sense.  Robert, you probably want to
check out and then mimic what we're doing in the rest
of Stan by trying to follow the Git flow process.  It's
described in the Stan manual and also linked from the
stan-dev/stan wiki.

**Comment by jgabry** [comment]
Here's a good description

**Comment by jgabry** [comment]
oops, here it is:

http://nvie.com/posts/a-successful-git-branching-model/

I think it's the same as the one linked to from the stan wiki

**Comment by robertgrant** [comment]
Thanks, I shall digest this. Need to git skill up.

**Comment by jgabry** [comment]
I like this condensed "cheat sheet"

https://education.github.com/git-cheat-sheet-education.pdf

as it has everything you'll need regularly without a lot of other git
commands that are confusing and typically not needed.
